### ISSUE TITLE
On Linux, I see now compiler error: `Type mismatch: cannot convert from GdkRGBA to int`

### ISSUE THREAD

**Issue by iloveeclipse** [eclipse-platform/eclipse.platform.swt#25]
@SyntevoAlex : on Linux, I see now compiler error: `Type mismatch: cannot convert from GdkRGBA to int` in org.eclipse.swt.tests.manual.Issue0021_HdcLeak_ImageCreateGdipImage

_Originally posted by @iloveeclipse in https://github.com/eclipse-platform/eclipse.platform.swt/pull/22#discussion_r843683796_

Introduced in #22.

**Comment by SyntevoAlex** [comment]
Sorry about this mistake! Please see #28 for a fix.

**Comment by iloveeclipse** [comment]
Thanks Alex, I was also surprised too seeing compilation error on Linux after tested original PR without issues on Windows. That's the moment one realizes that SWT API **is** platform dependent :-)

**Comment by SyntevoAlex** [comment]
And I realized that `ImageData.transparentPixel` wants a "pixel" but there's no explanation about its format (ARGB? RGBA? RGB? BGR?) and no easy means of obtaining one from `Color`. But alas, I guess I'm too lazy to fix that :(
