### ISSUE TITLE
Compilation in I-build: I20220721-0420

### ISSUE THREAD

**Issue by sravanlakkimsetti** [eclipse-platform/eclipse.platform.swt#267]
**Describe the bug**
We are getting compilation errors during I-build

**To Reproduce**
See https://ci.eclipse.org/releng/job/I-build-4.25/95/console

**Expected behavior**
Build should succeed without compilation errors

**Environment:**
1. Select the platform(s) on which the behavior is seen:
- - [x] All OS
- - [ ] Windows
- - [ ] Linux
- - [ ] macOS 

2. Additional OS info (e.g. OS version, Linux Desktop, etc)
centos 8

3. JRE/JDK version
 Java 11

**Version since**
 Eclipse or SWT version since when the behavior is seen latest I-build

**Workaround (or) Additional context**
Any known workarounds for the problem? No

**Comment by akurtakov** [comment]
I'm on it. It's caused by https://github.com/eclipse-platform/eclipse.platform.swt/commit/0b0d8663f993aece50455a1737dd17d5991de836 which I'll revert now.
