### ISSUE TITLE
Compilation error in Snippet382 on Linux/macOS

### ISSUE THREAD

**Issue by ptziegler** [eclipse-platform/eclipse.platform.swt#1460]
**Describe the bug**

This snippet sets the `nativeZoom` field of the GCData object. However, this field only exists on Windows, leading to a compilation error on both Linux and macOS.

https://github.com/eclipse-platform/eclipse.platform.swt/blob/ca113ca06e4e50bf46056fa46ef45f77998293ac/examples/org.eclipse.swt.snippets/src/org/eclipse/swt/snippets/Snippet382.java#L105-L113

**Screenshots**

![image](https://github.com/user-attachments/assets/68a30d77-92f7-47e5-8bdf-3bc44722e3dd)

**Environment:**
1. Select the platform(s) on which the behavior is seen:
- - [ ] All OS
- - [ ] Windows
- - [x] Linux
- - [x] macOS

**Comment by akurtakov** [comment]
Seems caused by https://github.com/eclipse-platform/eclipse.platform.swt/pull/1214

**Comment by HeikoKlare** [comment]
Looks like you have an invalidate state of a `.classpath` file in the snippets project. The snippet is Windows only and accordingly excluded from the classpath files for MacOS and Linux:
https://github.com/eclipse-platform/eclipse.platform.swt/blob/ca113ca06e4e50bf46056fa46ef45f77998293ac/examples/org.eclipse.swt.snippets/.classpath_cocoa#L5

https://github.com/eclipse-platform/eclipse.platform.swt/blob/ca113ca06e4e50bf46056fa46ef45f77998293ac/examples/org.eclipse.swt.snippets/.classpath_gtk#L5

You should remove the existing `.classpath` file in the snippet project and either copy and rename the correct or, if you have an Oomphed setup, perform setup tasks and have Oomph fix that for your.

**Comment by HeikoKlare** [comment]
You are showing the linked `.classpath` file of the SWT fragment (like `org.eclipse.swt.gtk.linux.x86_64`) , not of the snippets project (i.e., `org.eclipse.swt.snippets`). In the snippets project, there is no linking of the correct `.classpath` file. It is simply copied by the Oomph setup (or by hand, in a manual setup). This is how it looks like:

![image](https://github.com/user-attachments/assets/92442788-1a9a-4a0a-9f2e-2365bda50920)
