### PR TITLE
#25 Fix compilation error in test snippet on Linux

### LINKED ISSUE #25: On Linux, I see now compiler error: `Type mismatch: cannot convert from GdkRGBA to int`
@SyntevoAlex : on Linux, I see now compiler error: `Type mismatch: cannot convert from GdkRGBA to int` in org.eclipse.swt.tests.manual.Issue0021_HdcLeak_ImageCreateGdipImage

_Originally posted by @iloveeclipse in https://github.com/eclipse-platform/eclipse.platform.swt/pull/22#discussion_r843683796_

Introduced in #22.

### PR DESCRIPTION
**Pull request by SyntevoAlex**
Fixes #25
Regression from #21

Signed-off-by: Alexandr Miloslavskiy <alexandr.miloslavskiy@syntevo.com>

### CODE REVIEW

**Review by iloveeclipse — APPROVED** [review]
LGTM.
The one test failure is due https://github.com/eclipse-platform/eclipse.platform.swt/issues/27
